spring.application.name=logs-api

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/logsdb}
spring.datasource.username=${DB_USER:dogs}
spring.datasource.password=${DB_PASSWORD:dogspass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
