services:
  db:
    image: mysql:8.4
    container_name: exo08-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dogsdb
      MYSQL_USER: dogs
      MYSQL_PASSWORD: dogspass
    ports:
      - "3308:3306"          # port forwarding pour développer l'API en local
    volumes:
      - dogs-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-udogs", "-pdogspass"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: exo08-api
    environment:
      DB_URL: jdbc:mysql://db:3306/dogsdb
      DB_USER: dogs
      DB_PASSWORD: dogspass
    ports:
      - "8088:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  dogs-data:
